version: '3'
services:
  restaurant:
    build: .
    hostname: '${HOSTNAME}'
    container_name: '${PROJECT_NAME}'
    ports:
        - 3000:3000
    volumes:
      - '${PROJECT_ROOT}:/myapp'
    working_dir: /myapp
    environment:
      DB_HOST: 'restaurant_db'
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      RAILS_ENV: '${ENVIRONMENT}'
    depends_on:
      - 'restaurant_postgresql'
    links:
      - 'restaurant_postgresql'
    command: [ "rails", "server", "-b", "0.0.0.0" ]
    entrypoint: ./entrypoint.sh
  restaurant_postgresql:
    container_name: '${PROJECT_NAME}_postgresql'
    image: postgres:latest
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USER}'
    volumes:
      - /var/lib/postgresql/data
